# Server configurations
server:
  host: "localhost"
  port: 8088


# databaseName credentials
databaseName:
  acawsDBName: "awacs"
  acawsSmartDBName: "awacs_smart"
  smartStockistDBName: "SmartStockist"

# databaseConfig credentials
databaseConfig:
  host: "10.153.128.3"
  port: 1433
  user: "sqlserver"
  pass: "test"